// Generates a ready-to-deploy Budgeter app for one platform, as a plain folder (Node 20+, no dependencies).
//
//   node tools/create.mjs <platform> <target-dir>            new app (target must be empty or missing)
//   node tools/create.mjs <platform> <target-dir> --update   refresh the code, keep the config files
//
// Platforms: the folders in platforms/ (cloudflare, vercel-supabase). The target is normally a folder
// in the user's PRIVATE finance repo, e.g. ../my-finances/app. The output imports nothing from this
// repo: shared code (server/) is copied in and import paths are rewritten.
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const repo = resolve(fileURLToPath(new URL("..", import.meta.url)));
const [platform, target, flag] = process.argv.slice(2);
const platforms = readdirSync(join(repo, "platforms")).filter((d) => statSync(join(repo, "platforms", d)).isDirectory());
if (!platform || !target || !platforms.includes(platform) || (flag && flag !== "--update")) {
  console.error(`Usage: node tools/create.mjs <${platforms.join("|")}> <target-dir> [--update]`);
  process.exit(1);
}
const out = resolve(target);
const update = flag === "--update";
if (!update && existsSync(out) && readdirSync(out).length) {
  console.error(`${out} isn't empty. Use --update to refresh an existing app's code.`);
  process.exit(1);
}
if (out === repo || out.startsWith(repo + sep)) {
  console.error("Create the app outside this repo (in the user's private repo), so personal config never lands here.");
  process.exit(1);
}

// Per platform: where things go, and which files hold the user's settings (kept on --update).
const layouts = {
  cloudflare: {
    web: "public", server: "src",
    files: { "worker.js": "src/worker.js", "wrangler.jsonc": "wrangler.jsonc", "schema.sql": "schema.sql",
      "package.json": "package.json", "package-lock.json": "package-lock.json" },
    config: ["wrangler.jsonc", "package.json", "package-lock.json"],
  },
  "vercel-supabase": {
    web: "public", server: "api/_lib",
    files: { "api": "api", "vercel.json": "vercel.json", "schema.sql": "schema.sql", "cron.sql": "cron.sql", "package.json": "package.json", "auth.js": "public/auth.js" },
    config: ["vercel.json", "package.json"],
  },
};
const layout = layouts[platform];
if (!layout) { console.error(`No layout for ${platform} in tools/create.mjs yet.`); process.exit(1); }

const written = [];
const write = (dest, text) => {
  const path = join(out, dest);
  if (update && layout.config.includes(dest) && existsSync(path)) return;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text);
  written.push(dest);
};
const copyTree = (src, dest, transform) => {
  for (const name of readdirSync(src)) {
    const s = join(src, name), d = join(dest, name);
    if (statSync(s).isDirectory()) copyTree(s, d, transform);
    else if (/\.(js|mjs|json|jsonc|sql|html|css|webmanifest|md)$/.test(name)) write(d, transform ? transform(readFileSync(s, "utf8"), d) : readFileSync(s, "utf8"));
    else { mkdirSync(dirname(join(out, d)), { recursive: true }); cpSync(s, join(out, d)); written.push(d); }
  }
};

// Imports of ../server/*.js in platform code point at wherever the shared code lands in the output.
const rewrite = (text, dest) => text.replace(/(["'])(?:\.\.\/)+server\/([\w.-]+\.js)\1/g, (_, qt, file) => {
  let rel = relative(dirname(join(out, dest)), join(out, layout.server, file)).split(sep).join("/");
  if (!rel.startsWith(".")) rel = "./" + rel;
  return qt + rel + qt;
});

copyTree(join(repo, "app"), layout.web);
copyTree(join(repo, "server"), layout.server);
for (const [src, dest] of Object.entries(layout.files)) {
  const s = join(repo, "platforms", platform, src);
  if (!existsSync(s)) continue;
  if (statSync(s).isDirectory()) copyTree(s, dest, rewrite);
  else write(dest, rewrite(readFileSync(s, "utf8"), dest));
}
write(".gitignore", "node_modules/\n.wrangler/\n.vercel/\n.dev.vars\n.env*\n");

let version = "unknown";
try { version = execSync("git rev-parse --short HEAD", { cwd: repo, stdio: ["ignore", "pipe", "ignore"] }).toString().trim(); } catch {}
write("BUDGETER.md", `# Budgeter app (${platform})

Generated by \`tools/create.mjs\` from Budgeter (https://github.com/andytango/budgeter) at commit \`${version}\`.
Setup steps: \`platforms/${platform}/SETUP.md\` in that repo.

- \`${layout.web}/\`: the phone app (static files). \`panel.js\` + \`panel.css\` hold all rendering and projections.
- \`${layout.server}/api.js\`, \`${layout.server}/push.js\`: the shared API and Web Push code.
- The rest is ${platform}-specific: see SETUP.md.

To update to a newer Budgeter, run from a Budgeter checkout:
\`node tools/create.mjs ${platform} <this folder> --update\` (keeps ${layout.config.join(", ")}), then redeploy.
Local changes to other files are overwritten, so make lasting changes upstream or re-apply them.
`);

const left = written.filter((f) => /\.(jsonc?|js|sql)$/.test(f) && readFileSync(join(out, f), "utf8").includes("REPLACE_ME"));
console.log(`${update ? "Updated" : "Created"} ${platform} app in ${out} (${written.length} files).`);
if (left.length) console.log(`Fill in REPLACE_ME in: ${left.join(", ")}`);
console.log(`Next: follow platforms/${platform}/SETUP.md.`);
